/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCategoryRouteImport } from './routes/services.$category'
import { Route as ServicesCategoryIndexRouteImport } from './routes/services.$category.index'
import { Route as ServicesCategorySubRouteImport } from './routes/services.$category.$sub'
import { Route as ServicesCategorySubIndexRouteImport } from './routes/services.$category.$sub.index'
import { Route as ServicesCategorySubServiceRouteImport } from './routes/services.$category.$sub.$service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCategoryIndexRoute = ServicesCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesCategoryRoute,
} as any)
const ServicesCategorySubRoute = ServicesCategorySubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => ServicesCategoryRoute,
} as any)
const ServicesCategorySubIndexRoute =
  ServicesCategorySubIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServicesCategorySubRoute,
  } as any)
const ServicesCategorySubServiceRoute =
  ServicesCategorySubServiceRouteImport.update({
    id: '/$service',
    path: '/$service',
    getParentRoute: () => ServicesCategorySubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/services/$category': typeof ServicesCategoryRouteWithChildren
  '/services/': typeof ServicesIndexRoute
  '/services/$category/$sub': typeof ServicesCategorySubRouteWithChildren
  '/services/$category/': typeof ServicesCategoryIndexRoute
  '/services/$category/$sub/$service': typeof ServicesCategorySubServiceRoute
  '/services/$category/$sub/': typeof ServicesCategorySubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/admin/login': typeof AdminLoginRoute
  '/services': typeof ServicesIndexRoute
  '/services/$category': typeof ServicesCategoryIndexRoute
  '/services/$category/$sub/$service': typeof ServicesCategorySubServiceRoute
  '/services/$category/$sub': typeof ServicesCategorySubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/services/$category': typeof ServicesCategoryRouteWithChildren
  '/services/': typeof ServicesIndexRoute
  '/services/$category/$sub': typeof ServicesCategorySubRouteWithChildren
  '/services/$category/': typeof ServicesCategoryIndexRoute
  '/services/$category/$sub/$service': typeof ServicesCategorySubServiceRoute
  '/services/$category/$sub/': typeof ServicesCategorySubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/clients'
    | '/contact'
    | '/login'
    | '/news'
    | '/portfolio'
    | '/reviews'
    | '/services'
    | '/admin/login'
    | '/services/$category'
    | '/services/'
    | '/services/$category/$sub'
    | '/services/$category/'
    | '/services/$category/$sub/$service'
    | '/services/$category/$sub/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/clients'
    | '/contact'
    | '/login'
    | '/news'
    | '/portfolio'
    | '/reviews'
    | '/admin/login'
    | '/services'
    | '/services/$category'
    | '/services/$category/$sub/$service'
    | '/services/$category/$sub'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/clients'
    | '/contact'
    | '/login'
    | '/news'
    | '/portfolio'
    | '/reviews'
    | '/services'
    | '/admin/login'
    | '/services/$category'
    | '/services/'
    | '/services/$category/$sub'
    | '/services/$category/'
    | '/services/$category/$sub/$service'
    | '/services/$category/$sub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$category/': {
      id: '/services/$category/'
      path: '/'
      fullPath: '/services/$category/'
      preLoaderRoute: typeof ServicesCategoryIndexRouteImport
      parentRoute: typeof ServicesCategoryRoute
    }
    '/services/$category/$sub': {
      id: '/services/$category/$sub'
      path: '/$sub'
      fullPath: '/services/$category/$sub'
      preLoaderRoute: typeof ServicesCategorySubRouteImport
      parentRoute: typeof ServicesCategoryRoute
    }
    '/services/$category/$sub/': {
      id: '/services/$category/$sub/'
      path: '/'
      fullPath: '/services/$category/$sub/'
      preLoaderRoute: typeof ServicesCategorySubIndexRouteImport
      parentRoute: typeof ServicesCategorySubRoute
    }
    '/services/$category/$sub/$service': {
      id: '/services/$category/$sub/$service'
      path: '/$service'
      fullPath: '/services/$category/$sub/$service'
      preLoaderRoute: typeof ServicesCategorySubServiceRouteImport
      parentRoute: typeof ServicesCategorySubRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesCategorySubRouteChildren {
  ServicesCategorySubServiceRoute: typeof ServicesCategorySubServiceRoute
  ServicesCategorySubIndexRoute: typeof ServicesCategorySubIndexRoute
}

const ServicesCategorySubRouteChildren: ServicesCategorySubRouteChildren = {
  ServicesCategorySubServiceRoute: ServicesCategorySubServiceRoute,
  ServicesCategorySubIndexRoute: ServicesCategorySubIndexRoute,
}

const ServicesCategorySubRouteWithChildren =
  ServicesCategorySubRoute._addFileChildren(ServicesCategorySubRouteChildren)

interface ServicesCategoryRouteChildren {
  ServicesCategorySubRoute: typeof ServicesCategorySubRouteWithChildren
  ServicesCategoryIndexRoute: typeof ServicesCategoryIndexRoute
}

const ServicesCategoryRouteChildren: ServicesCategoryRouteChildren = {
  ServicesCategorySubRoute: ServicesCategorySubRouteWithChildren,
  ServicesCategoryIndexRoute: ServicesCategoryIndexRoute,
}

const ServicesCategoryRouteWithChildren =
  ServicesCategoryRoute._addFileChildren(ServicesCategoryRouteChildren)

interface ServicesRouteChildren {
  ServicesCategoryRoute: typeof ServicesCategoryRouteWithChildren
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryRoute: ServicesCategoryRouteWithChildren,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
